/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DesignPreset, SizePresetRule } from '../types/dtf';

export const DEFAULT_SIZING_RULES: SizePresetRule[] = [
  {
    sizeCategory: 'adult',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', 'Adult'],
    frontNameWidthInches: 13.0,
    frontNameHeightInches: 2.2,
    backNameWidthInches: 13.0,
    backNameHeightInches: 2.2,
    backNumberHeightInches: 9.5,
    frontNumberHeightInches: 4.0,
    sleeveNumberHeightInches: 3.5,
    sleeveBadgeWidthInches: 3.25,
  },
  {
    sizeCategory: 'youth',
    sizes: ['YXS', 'YS', 'YM', 'YL', 'YXL', 'Youth'],
    frontNameWidthInches: 9.6,
    frontNameHeightInches: 1.8,
    backNameWidthInches: 9.6,
    backNameHeightInches: 1.8,
    backNumberHeightInches: 7.6,
    frontNumberHeightInches: 3.0,
    sleeveNumberHeightInches: 2.75,
    sleeveBadgeWidthInches: 2.5,
  },
  {
    sizeCategory: 'infant',
    sizes: ['2T', '3T', '4T', '5T', 'Infant'],
    frontNameWidthInches: 7.8,
    frontNameHeightInches: 1.4,
    backNameWidthInches: 7.8,
    backNameHeightInches: 1.4,
    backNumberHeightInches: 6.1,
    frontNumberHeightInches: 2.25,
    sleeveNumberHeightInches: 2.0,
    sleeveBadgeWidthInches: 2.0,
  },
];

export const DEFAULT_DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 'preset-milan-2007',
    code: 'SJ-Y5EMT',
    name: 'AC Milan Classic 2007',
    category: 'Serie A',
    league: 'Serie A',
    season: '2006-07',
    sport: 'soccer',
    description: 'Kaka Champions League Final style with gold stroke and red/black accenting.',
    isDefault: true,
    defaultTeamName: 'AC MILAN',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 12,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Oswald', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#D4AF37', width: 4.5, join: 'round' },
        { enabled: false, color: '#000000', width: 2, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Oswald', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#D4AF37', width: 4.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Oswald', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFFFFF',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#D4AF37', width: 5, join: 'round' },
        { enabled: false, color: '#000000', width: 2, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 4,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-real-madrid-2014',
    code: 'SJ-S6NGQ',
    name: 'Real Madrid 2014-15',
    category: 'La Liga',
    league: 'La Liga',
    season: '2014-15',
    sport: 'soccer',
    description: 'La Decima championship victory design with cobalt blue and gold metallic font.',
    isDefault: false,
    defaultTeamName: 'REAL MADRID',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 8,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFD700',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 8,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 4, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFD700',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 8,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 3.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFD700',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 4.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-barcelona-2016',
    code: 'BARCELONA 2016-17',
    name: 'Barcelona 2016-17',
    category: 'La Liga',
    league: 'La Liga',
    season: '2016-17',
    sport: 'soccer',
    description: 'MSN historic treble era typography with sharp geometric curves and navy outline.',
    isDefault: false,
    defaultTeamName: 'BARCELONA',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 14,
    nameWidthInches: 13.0,
    nameHeightInches: 2.3,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 2.3,
      fillColor: '#FFFFFF',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 14,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#DC2626', width: 4, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 2.3,
      fillColor: '#FFFFFF',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 14,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#DC2626', width: 3.5, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFFFFF',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#DC2626', width: 4.5, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 2.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#0F172A',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-real-madrid-2023',
    code: 'REAL MADRID 2023-24',
    name: 'Real Madrid 2023-24',
    category: 'La Liga',
    league: 'La Liga',
    season: '2023-24',
    sport: 'soccer',
    description: 'Gold & Navy 15th UCL Championship Champions style with Teko typography.',
    isDefault: false,
    defaultTeamName: 'REAL MADRID',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 10,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 4,
    frontText: {
      fontFamily: "'Teko', sans-serif",
      fontSizeInches: 2.4,
      fillColor: '#1A237E',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 10,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#EAB308', width: 3.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Teko', sans-serif",
      fontSizeInches: 2.4,
      fillColor: '#1A237E',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 10,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#EAB308', width: 3, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Teko', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#1A237E',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#EAB308', width: 4, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-argentina-2022',
    code: 'ARGENTINA 2022',
    name: 'Argentina National Team',
    category: 'International',
    league: 'International',
    season: '2022 World Cup',
    sport: 'soccer',
    description: 'World Cup 3-Star Champions font with futuristic Orbitron angular geometry.',
    isDefault: false,
    defaultTeamName: 'ARGENTINA',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 6,
    nameWidthInches: 13.0,
    nameHeightInches: 2.1,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Orbitron', sans-serif",
      fontSizeInches: 2.1,
      fillColor: '#000000',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 6,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#38BDF8', width: 3, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: false,
        color: '#000000',
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        style: 'soft_shadow',
      },
    },
    backName: {
      fontFamily: "'Orbitron', sans-serif",
      fontSizeInches: 2.1,
      fillColor: '#000000',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 6,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#38BDF8', width: 2.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: false,
        color: '#000000',
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        style: 'soft_shadow',
      },
    },
    backNumber: {
      fontFamily: "'Orbitron', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#000000',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#38BDF8', width: 4, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: false,
        color: '#000000',
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        style: 'soft_shadow',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-man-utd-2008',
    code: 'MAN UNITED 2008',
    name: 'Manchester United',
    category: 'Premier League',
    league: 'Premier League',
    season: '2007-08',
    sport: 'soccer',
    description: 'Moscow 2008 Champions League glory style with bold collegiate varsity serif.',
    isDefault: false,
    defaultTeamName: 'MANCHESTER UNITED',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 12,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Graduate', Impact, sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#DC2626',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#000000', width: 3, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Graduate', Impact, sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#DC2626',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#000000', width: 2.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Graduate', Impact, sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#DC2626',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#000000', width: 4, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-inter-miami-2023',
    code: 'INTER MIAMI 2023',
    name: 'Inter Miami CF',
    category: 'MLS',
    league: 'MLS',
    season: '2023-24',
    sport: 'soccer',
    description: 'Leagues Cup Champions vibrant Flamingo Pink with jet black contrast and Montserrat font.',
    isDefault: false,
    defaultTeamName: 'INTER MIAMI',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 10,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 4,
    frontText: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#F7B5CD',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 10,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#000000', width: 3, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#F7B5CD',
      letterSpacing: 4,
      warpStyle: 'arc_top',
      warpBend: 10,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#000000', width: 2.5, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#F7B5CD',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#000000', width: 4, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-psg-2021',
    code: 'PSG 2021-22',
    name: 'Paris Saint-Germain',
    category: 'Ligue 1',
    league: 'Ligue 1',
    season: '2021-22',
    sport: 'soccer',
    description: 'Parc des Princes star-studded galaxy style with French Navy and pure white typography.',
    isDefault: false,
    defaultTeamName: 'PARIS SG',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 12,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 3.5, join: 'round' },
        { enabled: true, color: '#DC2626', width: 1.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 3, join: 'round' },
        { enabled: true, color: '#DC2626', width: 1.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Montserrat', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFFFFF',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#1E3A8A', width: 4.5, join: 'round' },
        { enabled: true, color: '#DC2626', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-arsenal-2003',
    code: 'ARSENAL 2003-04',
    name: 'Arsenal Invincibles',
    category: 'Premier League',
    league: 'Premier League',
    season: '2003-04',
    sport: 'soccer',
    description: 'Highbury unvanquished legacy aesthetic with fiery scarlet red and clean high-impact Bebas Neue.',
    isDefault: false,
    defaultTeamName: 'ARSENAL',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 14,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 2.3,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 14,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#DC2626', width: 4, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 2.3,
      fillColor: '#FFFFFF',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 14,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#DC2626', width: 3.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFFFFF',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#DC2626', width: 4.5, join: 'round' },
        { enabled: false, color: '#000000', width: 2, join: 'round' },
        { enabled: false, color: '#FFFFFF', width: 2, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
  {
    id: 'preset-brazil-2002',
    code: 'BRAZIL 2002',
    name: 'Brazil 2002 Penta',
    category: 'International',
    league: 'International',
    season: '2002 World Cup',
    sport: 'soccer',
    description: 'Penta Champions Samba Yellow with forest green and blue speed arcs.',
    isDefault: false,
    defaultTeamName: 'BRASIL',
    defaultGarmentType: 'soccer_kit',
    defaultGarmentColor: '#0F172A',
    defaultFabricTexture: 'poly_knit',
    arcCurveAngle: 12,
    nameWidthInches: 13.0,
    nameHeightInches: 2.2,
    numberHeightInches: 9.5,
    letterSpacingPx: 3,
    frontText: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFD700',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#15803D', width: 3.5, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 1.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 3,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backName: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 2.2,
      fillColor: '#FFD700',
      letterSpacing: 3,
      warpStyle: 'arc_top',
      warpBend: 12,
      uppercase: true,
      strokes: [
        { enabled: true, color: '#15803D', width: 3, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 1.5, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    backNumber: {
      fontFamily: "'Anton', sans-serif",
      fontSizeInches: 9.5,
      fillColor: '#FFD700',
      letterSpacing: 2,
      warpStyle: 'flat',
      warpBend: 0,
      uppercase: true,
      numberStyle: 'all',
      digitSpacing: 4,
      showZeroPrefix: false,
      strokes: [
        { enabled: true, color: '#15803D', width: 4, join: 'round' },
        { enabled: true, color: '#1E3A8A', width: 2, join: 'round' },
        { enabled: false, color: '#000000', width: 1, join: 'round' },
      ],
      shadow: {
        enabled: true,
        color: '#000000',
        offsetX: 3,
        offsetY: 4,
        blur: 0,
        style: 'hard_extrusion',
      },
    },
    sizingRules: DEFAULT_SIZING_RULES,
  },
];

export const ROLL_PRESETS = [
  { id: 'roll_39', name: '39" Commercial Roll (SPD Standard)', widthInches: 39.0, maxPrintableWidthInches: 38.5 },
  { id: 'roll_24', name: '24" Industrial Roll', widthInches: 24.0, maxPrintableWidthInches: 23.5 },
  { id: 'roll_22', name: '22" Desktop Roll', widthInches: 22.0, maxPrintableWidthInches: 21.5 },
  { id: 'sheet_a3', name: '13" x 19" (A3+ Sheet)', widthInches: 13.0, maxPrintableWidthInches: 12.5 },
];

export const SAMPLE_TEAM_ROSTERS: Record<string, { teamName: string; sport: string; items: Array<{ orderNumber: string; playerName: string; playerNumber: string; garmentSize: string; garmentColor: string; quantity: number; notes: string }> }> = {
  baseball: {
    teamName: 'SPIDERS',
    sport: 'baseball',
    items: [
      { orderNumber: 'ORD-101', playerName: 'PARKER', playerNumber: '07', garmentSize: 'L', garmentColor: '#0F172A', quantity: 1, notes: 'Captain' },
      { orderNumber: 'ORD-102', playerName: 'MORALES', playerNumber: '10', garmentSize: 'M', garmentColor: '#0F172A', quantity: 1, notes: 'Shortstop' },
      { orderNumber: 'ORD-103', playerName: 'STACY', playerNumber: '24', garmentSize: 'S', garmentColor: '#0F172A', quantity: 1, notes: 'Pitcher' },
      { orderNumber: 'ORD-104', playerName: 'OSBORN', playerNumber: '01', garmentSize: 'XL', garmentColor: '#0F172A', quantity: 1, notes: 'Outfield' },
      { orderNumber: 'ORD-105', playerName: 'BROCK', playerNumber: '99', garmentSize: '2XL', garmentColor: '#0F172A', quantity: 1, notes: 'First Base' },
    ],
  },
  basketball: {
    teamName: 'VIPERS',
    sport: 'basketball',
    items: [
      { orderNumber: 'BKB-201', playerName: 'JOHNSON', playerNumber: '23', garmentSize: 'XL', garmentColor: '#1E1B4B', quantity: 1, notes: 'Point Guard' },
      { orderNumber: 'BKB-202', playerName: 'DAVIS', playerNumber: '03', garmentSize: '2XL', garmentColor: '#1E1B4B', quantity: 1, notes: 'Forward' },
      { orderNumber: 'BKB-203', playerName: 'BRYANT', playerNumber: '08', garmentSize: 'L', garmentColor: '#1E1B4B', quantity: 1, notes: 'Guard' },
    ],
  },
  soccer: {
    teamName: 'TITANS FC',
    sport: 'soccer',
    items: [
      { orderNumber: 'SOC-301', playerName: 'KAKA', playerNumber: '22', garmentSize: 'L', garmentColor: '#090A0F', quantity: 1, notes: 'Midfield' },
      { orderNumber: 'SOC-302', playerName: 'MESSI', playerNumber: '10', garmentSize: 'M', garmentColor: '#090A0F', quantity: 1, notes: 'Forward' },
      { orderNumber: 'SOC-303', playerName: 'RONALDO', playerNumber: '07', garmentSize: 'L', garmentColor: '#090A0F', quantity: 1, notes: 'Striker' },
    ],
  },
};

export const SAMPLE_ORDER_TEXT_1 = `SJ-Y5EMT, KAKA, 22
SJ-S6NGQ, MESSI, 10
BARCELONA 2016-17, NEYMAR, 11
REAL MADRID 2023-24, RONALDO, 7
ARGENTINA 2022, MESSI, 10
MAN UNITED 2008, RONALDO, 7, Adult
INTER MIAMI 2023, MESSI, 10, Youth
PSG 2021-22, MBAPPE, 7, Adult
ARSENAL 2003-04, HENRY, 14, Adult
BRAZIL 2002, RONALDINHO, 11, Adult`;

export const SAMPLE_ORDER_TEXT_2 = `REAL MADRID 2023-24, BELLINGHAM, 5, Adult
ARGENTINA 2022, DI MARIA, 11, Adult
INTER MIAMI 2023, SUAREZ, 9, Adult
MAN UNITED 2008, ROONEY, 10, Adult
BARCELONA 2016-17, SUAREZ, 9, Adult
BRAZIL 2002, RIVALDO, 10, Adult
PSG 2021-22, NEYMAR, 10, Adult
ARSENAL 2003-04, BERGKAMP, 10, Adult
SJ-Y5EMT, MALDINI, 3, Adult
SJ-S6NGQ, INIESTA, 8, Adult`;
